"""Audio Player plugin — play, stop, and check audio playback.

Allows the LLM to play audio files (WAV, MP3, etc.) on the local
system, stop playback, and check current status. Used for alarms,
notifications, music, and generated audio (e.g. from sandbox).
"""

import json
from dataclasses import dataclass
from typing import Any

from ....lib.function_calling import Tool
from ....lib.security import TIER_WRITE_DATA, TIER_READONLY
from ....lib.plugin_base import PluginContext


@dataclass
class AudioPlayerPlugin:
    name: str = "audio_player"
    display_name: str = "Audio Player"

    def is_available(self) -> bool:
        return True

    def get_tools(self, ctx: PluginContext) -> list[Tool]:

        async def _play(file_path: str) -> str:
            """Play an audio file on the local system."""
            from ....lib.audio_manager import audio_manager
            ok = audio_manager.play(file_path)
            if ok:
                return json.dumps({"success": True, "playing": file_path})
            return json.dumps({"success": False, "error": f"Could not play {file_path}"})

        async def _stop() -> str:
            """Stop current audio playback."""
            from ....lib.audio_manager import audio_manager
            stopped = audio_manager.stop()
            return json.dumps({"success": True, "stopped": stopped})

        async def _status() -> str:
            """Get current audio playback status."""
            from ....lib.audio_manager import audio_manager
            return json.dumps(audio_manager.status())

        return [
            Tool(
                name="audio_play",
                tier=TIER_WRITE_DATA,
                description=(
                    "Play an audio file on the local system (speakers). "
                    "Supports WAV, MP3, OGG, FLAC. Use this for alarms, "
                    "notifications, music, or audio files generated by the sandbox. "
                    "Any currently playing audio will be stopped first."
                ),
                parameters={
                    "type": "object",
                    "properties": {
                        "file_path": {
                            "type": "string",
                            "description": "Absolute path to the audio file (e.g. /tmp/aifred_wecker.wav)",
                        },
                    },
                    "required": ["file_path"],
                },
                executor=_play,
            ),
            Tool(
                name="audio_stop",
                tier=TIER_READONLY,
                description="Stop any currently playing audio immediately.",
                parameters={
                    "type": "object",
                    "properties": {},
                },
                executor=_stop,
            ),
            Tool(
                name="audio_status",
                tier=TIER_READONLY,
                description="Check if audio is currently playing and which file.",
                parameters={
                    "type": "object",
                    "properties": {},
                },
                executor=_status,
            ),
        ]

    def get_prompt_instructions(self, lang: str) -> str:
        return ""

    def get_ui_status(self, tool_name: str, tool_args: dict[str, Any], lang: str) -> str:
        if tool_name == "audio_play":
            return f"Playing: {tool_args.get('file_path', '')}"
        if tool_name == "audio_stop":
            return "Stopping audio..."
        return ""


plugin = AudioPlayerPlugin()
